# Generated by Django 4.2 on 2026-04-25 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_entidad_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo_saq', models.CharField(max_length=100)),
                ('tipo_saq_primario', models.CharField(choices=[('A', 'SAQ A'), ('AEP', 'SAQ A-EP'), ('B', 'SAQ B'), ('BIP', 'SAQ B-IP'), ('C', 'SAQ C'), ('CTV', 'SAQ C-VT'), ('D-COMERCIO', 'SAQ D Comercio'), ('D-PROVEEDOR', 'SAQ D Proveedor')], max_length=20)),
                ('pregunta_es', models.TextField()),
                ('pregunta_en', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('saq_recomendado', models.CharField(blank=True, choices=[('A', 'SAQ A'), ('AEP', 'SAQ A-EP'), ('B', 'SAQ B'), ('BIP', 'SAQ B-IP'), ('C', 'SAQ C'), ('CTV', 'SAQ C-VT'), ('D-COMERCIO', 'SAQ D Comercio'), ('D-PROVEEDOR', 'SAQ D Proveedor')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saq.preguntasaq')),
                ('pretest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='saq.pretest')),
            ],
            options={
                'unique_together': {('pretest', 'pregunta')},
            },
        ),
    ]
