# Generated by Django 4.2 on 2026-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasaq',
            name='saq_tipo',
            field=models.CharField(default='D', max_length=10),
        ),
    ]
