# Generated by Django 4.2 on 2026-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntasaq',
            options={'ordering': ['numero']},
        ),
        migrations.RemoveField(
            model_name='preguntasaq',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='max_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='opciones_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='seccion_aoc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='tipo_input',
            field=models.CharField(choices=[('elegibilidad', 'Sí / No / N/A / No probado'), ('checkbox_si_no', 'Sí / No'), ('checkbox_multi', 'Selección múltiple'), ('select', 'Lista desplegable'), ('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha')], default='texto_corto', max_length=50),
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='version_pci',
            field=models.CharField(default='4.0.1', max_length=10),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='tipo_saq',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='tipo_saq_primario',
            field=models.CharField(choices=[('A', 'SAQ A'), ('AEP', 'SAQ A-EP'), ('B', 'SAQ B'), ('BIP', 'SAQ B-IP'), ('C', 'SAQ C'), ('CTV', 'SAQ C-VT'), ('D-COMERCIO', 'SAQ D Comercio'), ('D-PROVEEDOR', 'SAQ D Proveedor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='respuestapretest',
            name='respuesta_texto',
            field=models.TextField(),
        ),
    ]
