# Generated by Django 4.2 on 2026-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saq', '0002_preguntasaq_saq_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
