# Generated by Django 4.2 on 2026-04-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_entidad_creado_por_and_more'),
        ('saq', '0002_alter_preguntasaq_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntasaq',
            options={'ordering': ['numero'], 'verbose_name': 'Pregunta SAQ', 'verbose_name_plural': 'Preguntas SAQ'},
        ),
        migrations.AlterModelOptions(
            name='pretest',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'PreTest', 'verbose_name_plural': 'PreTests'},
        ),
        migrations.AlterModelOptions(
            name='respuestapretest',
            options={'verbose_name': 'Respuesta PreTest', 'verbose_name_plural': 'Respuestas PreTest'},
        ),
        migrations.RemoveField(
            model_name='preguntasaq',
            name='tipo_saq_primario',
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='tipos_saq_extra',
            field=models.CharField(blank=True, default='', help_text='SAQs adicionales separados por coma. Ej: AEP,B', max_length=200),
        ),
        migrations.AddField(
            model_name='pretest',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='opciones_json',
            field=models.JSONField(blank=True, help_text='Lista de opciones para checkbox_multi o select', null=True),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='seccion_aoc',
            field=models.CharField(blank=True, default='Part 2h. Eligibility', max_length=100),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='tipo_input',
            field=models.CharField(choices=[('elegibilidad', 'Sí / No / N/A / No probado'), ('checkbox_si_no', 'Sí / No'), ('checkbox_multi', 'Selección múltiple (casillas)'), ('select', 'Lista desplegable'), ('texto_corto', 'Texto corto (≤ 200 car.)'), ('texto_largo', 'Texto largo (≤ 500 car.)'), ('numero', 'Número entero'), ('fecha', 'Fecha')], default='elegibilidad', max_length=30),
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='tipo_saq',
            field=models.CharField(choices=[('A', 'SAQ A'), ('AEP', 'SAQ A-EP'), ('B', 'SAQ B'), ('BIP', 'SAQ B-IP'), ('C', 'SAQ C'), ('CTV', 'SAQ C-VT'), ('D-COMERCIO', 'SAQ D Comercio'), ('D-PROVEEDOR', 'SAQ D Proveedor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretests', to='users.entidad'),
        ),
        migrations.AlterField(
            model_name='pretest',
            name='estado',
            field=models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestapretest',
            name='respuesta_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
