# Generated by Django 4.2 on 2026-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saq', '0003_alter_requisito_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAQTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntasaq',
            name='saq_tipo',
        ),
        migrations.AlterField(
            model_name='preguntasaq',
            name='tipo_respuesta',
            field=models.CharField(default='SI/NO', max_length=30),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='saq_tipos',
            field=models.ManyToManyField(to='saq.saqtipo'),
        ),
    ]
