# Generated by Django 4.2 on 2026-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saq', '0004_saqtipo_remove_preguntasaq_saq_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntasaq',
            name='saq_tipos',
        ),
        migrations.AlterField(
            model_name='requisito',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='RespuestaSAQ',
        ),
        migrations.DeleteModel(
            name='SAQTipo',
        ),
        migrations.AddField(
            model_name='preguntasaq',
            name='saqs',
            field=models.ManyToManyField(to='saq.saq'),
        ),
    ]
