# Generated by Django 4.2 on 2026-04-20 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(max_length=150)),
                ('tiempo_sesion', models.IntegerField()),
                ('idioma', models.CharField(default='es', max_length=20)),
                ('zona_horaria', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('recordatorio', 'Recordatorio')], max_length=20, unique=True)),
                ('dias_antes', models.IntegerField()),
                ('canal', models.CharField(choices=[('correo', 'Correo'), ('sistema', 'Sistema')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_dashboard', 'Puede ver dashboard'), ('ver_usuarios', 'Puede ver usuarios'), ('gestionar_usuarios', 'Puede gestionar usuarios'), ('ver_entidades', 'Puede ver entidades'), ('gestionar_entidades', 'Puede gestionar entidades'), ('ver_evidencias', 'Puede ver evidencias'), ('gestionar_renovacion', 'Puede gestionar renovación'), ('gestionar_configuracion', 'Puede gestionar configuración')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud_minima', models.IntegerField(default=8)),
                ('requiere_numeros', models.BooleanField(default=True)),
                ('requiere_mayusculas', models.BooleanField(default=True)),
                ('requiere_simbolos', models.BooleanField(default=True)),
                ('dias_vigencia', models.IntegerField()),
                ('intentos_fallidos', models.IntegerField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=20)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('dba', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
