# Generated by Django 4.2 on 2026-04-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_saq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='users.tiposaq')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('referencia_pci', models.CharField(blank=True, max_length=50)),
                ('tipos_saq', models.ManyToManyField(related_name='preguntas', to='users.tiposaq')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEnSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.preguntasaq')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='users.seccionsaq')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
