# Generated by Django 4.2 on 2026-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntapretest',
            old_name='texto',
            new_name='texto_es',
        ),
        migrations.AddField(
            model_name='preguntapretest',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preguntapretest',
            name='saq_destino',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='preguntapretest',
            name='texto_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preguntapretest',
            name='version_pci',
            field=models.CharField(default='4.0.1', max_length=10),
        ),
        migrations.AlterField(
            model_name='respuestapretest',
            name='respuesta',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
    ]
