# Generated by Django 4.2 on 2026-04-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEnSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta en sección',
                'verbose_name_plural': 'Preguntas en sección',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.SlugField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de SAQ',
                'verbose_name_plural': 'Tipos de SAQ',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeccionSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_saq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='users.tiposaq')),
            ],
            options={
                'verbose_name': 'Sección SAQ',
                'verbose_name_plural': 'Secciones SAQ',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaSAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_respuesta', models.CharField(choices=[('si_no_na', 'Sí / No / N/A')], default='si_no_na', max_length=20)),
                ('referencia_pci', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('secciones', models.ManyToManyField(related_name='preguntas', through='users.PreguntaEnSeccion', to='users.seccionsaq')),
            ],
            options={
                'verbose_name': 'Pregunta SAQ',
                'verbose_name_plural': 'Preguntas SAQ',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='preguntaenseccion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.preguntasaq'),
        ),
        migrations.AddField(
            model_name='preguntaenseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seccionsaq'),
        ),
        migrations.AlterUniqueTogether(
            name='preguntaenseccion',
            unique_together={('pregunta', 'seccion')},
        ),
    ]
