# Generated by Django 4.2 on 2026-04-21 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logauditoria_target_user_alter_logauditoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
