# Generated by Django 4.2 on 2026-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_texto_preguntapretest_texto_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_dashboard', 'Puede ver dashboard'), ('ver_usuarios', 'Puede ver usuarios'), ('gestionar_usuarios', 'Puede gestionar usuarios'), ('ver_entidades', 'Puede ver entidades'), ('gestionar_entidades', 'Puede gestionar entidades'), ('ver_saq', 'Puede ver SAQ'), ('editar_saq', 'Puede editar SAQ'), ('usar_pretest', 'Puede usar PreTest'), ('ver_evidencias', 'Puede ver evidencias'), ('gestionar_renovacion', 'Puede gestionar renovación')],
            },
        ),
    ]
