# Generated by Django 4.2 on 2026-04-21 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_entidad_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entidad',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
