# Generated by Django 4.2 on 2026-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_entidad_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicaseguridad',
            name='dias_vigencia',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='politicaseguridad',
            name='intentos_fallidos',
            field=models.IntegerField(default=5),
        ),
    ]
