# Generated by Django 4.2 on 2026-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_politicaseguridad_dias_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionconfig',
            name='estilo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('danger', 'Urgente'), ('success', 'Éxito')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacionconfig',
            name='tipo',
            field=models.CharField(choices=[('vencimiento_certificacion', 'Vencimiento de certificación'), ('vencimiento_contrato', 'Vencimiento de contrato'), ('pretest_pendiente', 'PreTest pendiente'), ('renovacion_proxima', 'Renovación próxima')], max_length=40, unique=True),
        ),
    ]
