# Generated by Django 4.2 on 2026-05-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_notificacionconfig_estilo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login_ok', models.DateTimeField(blank=True, null=True)),
                ('contrasena_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('forzar_cambio', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
