# Generated by Django 4.2 on 2026-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_perfilseguridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='dba',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_empresa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
