# Generated by Django 4.2 on 2026-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('ASV', 'ASV Scan'), ('SAQ', 'SAQ'), ('POLITICA', 'Política'), ('CAPTURA', 'Captura'), ('FIREWALL', 'Firewall'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
