# Generated by Django 4.2 on 2026-05-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_evidencia_activa_evidencia_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisossistema',
            options={'permissions': [('ver_dashboard', 'Puede ver dashboard'), ('ver_usuarios', 'Puede ver usuarios'), ('gestionar_usuarios', 'Puede gestionar usuarios'), ('ver_entidades', 'Puede ver entidades'), ('gestionar_entidades', 'Puede gestionar entidades'), ('ver_evidencias', 'Puede ver evidencias'), ('gestionar_evidencias', 'Puede gestionar evidencias'), ('gestionar_renovacion', 'Puede gestionar renovación'), ('gestionar_configuracion', 'Puede gestionar configuración')]},
        ),
    ]
